# Generated by Django 4.2.30 on 2026-07-06 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code_text', models.CharField(default='Unknown', max_length=255)),
                ('value_text', models.CharField(blank=True, default='', max_length=500)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='records.patient')),
            ],
        ),
    ]
